apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_DATASOURCE_URL: {{ .Values.env.SPRING_DATASOURCE_URL | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.env.SPRING_DATASOURCE_USERNAME | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.env.SPRING_DATASOURCE_PASSWORD | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.env.JWT_SECRET_KEY | b64enc | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.env.TWILIO_ACCOUNT_SID | b64enc | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.env.TWILIO_AUTH_TOKEN | b64enc | quote }}
  TWILIO_PHONE_NUMBER: {{ .Values.env.TWILIO_PHONE_NUMBER | b64enc | quote }}
  IYZICO_API_KEY: {{ .Values.env.IYZICO_API_KEY | b64enc | quote }}
  IYZICO_SECRET_KEY: {{ .Values.env.IYZICO_SECRET_KEY | b64enc | quote }}
